export default [
{
    id: 1,
    date: '02-01-2021',
    titre: 'Developper frontend',
    type: 'Plein temps',
    localisation:'Libreville',
    nomEntreprise:'JobberTech',
    email: 'JobberTech@gmail.com',
    salaire: '200k-400k',
    categorie:'Informatique',
    genre:'emploi',
    lien: 'jobbertech.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},
{
    id: 2,
    date: '03-01-2021',
    titre: 'Developper backend',
    type: 'Temps partiel',
    localisation:'Port-Gentil',
    nomEntreprise:'Total',
    email: 'totalgabon@gmail.com',
    salaire: '200k-400k',
    categorie:'Informatique',
    genre:'emploi',
    lien: 'total.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},
{
    id: 3,
    date: '04-01-2021',
    titre: 'Secrétaire',
    type: 'Temps partiel',
    localisation:'Libreville',
    nomEntreprise:'Urban Fm',
    email: 'urbanfm@gmail.com',
    salaire: '100k-150k',
    categorie:'RH',
    genre:'stage',
    lien: 'urbanfm.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},
{
    id: 4,
    date: '05-01-2021',
    titre: 'Ingénieur Agronome',
    type: 'Temps plein',
    localisation:'Libreville',
    nomEntreprise:'OLAM GABON',
    email: 'olamgabon@gmail.com',
    salaire: '400k-800k',
    categorie:'Agriculture',
    genre:'emploi',
    lien: 'olamgabon.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},
{
    id: 5,
    date: '06-01-2021',
    titre: 'Nounou',
    type: 'Temps partiel',
    localisation:'Owendo',
    nomEntreprise:'Jobs Gabon',
    email: 'jobsgabon@gmail.com',
    salaire: '100k-150k',
    categorie:'Menage',
    genre:'emploi',
    lien: 'jobsgabon.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},
{
    id: 6,
    date: '07-01-2021',
    titre: 'Comptable',
    type: 'Temps partiel',
    localisation:'Librville',
    nomEntreprise:'Jobs Gabon',
    email: 'jobsgabon@gmail.com',
    salaire: '300k-400k',
    categorie:'Menage',
    genre:'emploi',
    lien: 'jobsgabon.com',
    description: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. '
},

]